### PR TITLE
Create a new "Sample app"

### PR DESCRIPTION
**Pull request by jotak**
Restore in progress through this sample app:

- Alert data
- Predictive data
- Area charts
- Bar charts
- Scatter lines

### CODE REVIEW

**Comment by jotak** [comment]
Screenshots: http://imgur.com/a/kqRgN

**Comment by jotak** [comment]
Note, most of the files under "example" directory are angular-cli generated files. Code lies mostly in `sample.component.*`

**Comment by jotak** [comment]
More screens: http://imgur.com/a/G47gE

**Review by mtho11 — APPROVED** [review]
Good to see this back in! Nice.

**Pull request merged**
