### PR TITLE
Refactor (some) charts to update vs delete & recreate

### PR DESCRIPTION
**Pull request by ammendonca**
Previously charts were being destroyed and recreated from scratch at
every refresh. With these changes only the dynamic elements are updated,
resulting in new possibilities (eg: animations/transitions) and helps to.
resolve some existing issues.

Also resolves an issue with area chart hide-high-low-values not working.

### CODE REVIEW

**Comment by pilhuhn** [comment]
Cool stuff. Could we use enter+exit from d3 instead: http://d3js.org/#enter-exit that looks like the most natural choice?

**Comment by ammendonca** [comment]
We can, I hope :) I've started by using it but faced some issues where chart was updating but keeping previous chart lines at the same time, so fallback to this simpler approach. Something to revisit aloing with a couple more fixes still missing.

Thanks for the feedback!

**Comment by mtho11** [comment]
I'm seeing some issues here. 
1) On metrics chart the layering is off. Alerts and others.
2) once you drag zoom, the zoomed in range  data points are not lining up with the lines.

Here is a video clip to illustrate better: https://vimeo.com/144042301

**Comment by ammendonca** [comment]
Mike, thanks for the feedback and the video, it was helpful to identify the problem. This commit fixes most of it, still seeing some alert ranges over the line in certain conditions, figuring out why.

**Comment by mtho11** [comment]
We'll circle back next week to better address this '@' vs '=' in a consistent manner.
This is the actual issue fwiw: http://stackoverflow.com/questions/25799363/passing-boolean-value-into-directive
As we discussed offline this afternoon, we have some alternatives. The best seems to be change all attributes to '=' so we get consistent argurment passing (no "myVar" vs "{{myVar}}" mix) but we also want to have the directives not be able to change the data. Clients should know that the hawkular-charting directives can't alter the data that the application is passing in. So adding 'const' variables in combination with '=' would seem to accomplish our needs.

I'd also like to ask the Hawtio guys about what they do.

**Pull request merged**
