### PR TITLE
Fix bug with showing Forecast data if we are drag-selecting a range. …

### PR DESCRIPTION
**Pull request by mtho11**
…Once we start to drag select a subselection of the range the forecast cone goes away at this point since it is no longer valid. Only show the forecast rendering on first display of original data once we start driling down into the data it is no longer relevant.

### CODE REVIEW

**Comment by mtho11** [comment]
Merged #149

**Comment by abonas** [comment]
@mtho11 are there enough reviewers and maintainers for the hawkular charts repo? I see that you commit and merge the PRs on your own.
Also why commits such as "fix trailing whitespace" are standalone commits on their own? do they have any importance in git log in this repo?

**Comment by mtho11** [comment]
@abonas Reviewers/committers welcome. Please add yourself. I don't have privs to add you but I think Heiko can.

**Comment by mtho11** [comment]
The error fix whitespace wasn't caught locally and only showed up with Travis. It was caught by tslint on Travis (just like the rubocop issues).

**Pull request merged**
